[package]
name = "advent2021"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sscanf = "0.1.4"
lazy_static = "1.4.0"
indicatif = "0.16.2"

[profile.release]
debug = true
